# tools/templates/.github/workflows/ci_match_retriever_ncaa.yml
name: CI

on:
  push:
    paths:
      - 'libs/match_retriever_ncaa/**'
  pull_request:
    paths:
      - 'libs/match_retriever_ncaa/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r $(git rev-parse --show-toplevel)/pip-requirements.txt
        pip install -r $(git rev-parse --show-toplevel)/dev-requirements.txt
        pip install -r libs/match_retriever_ncaa/requirements.txt

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest